# Overrides docker-compose.yml for development mode
# Usage:
#   docker-compose -f docker-compose.yml -f docker-compose.devel.yml ...
#
version: '3.7'
services:

  webclient:
    image: services_webclient:dev
    build:
      target: development
    volumes:
      - './web/client:/home/scu/client'
    command: >
      compile --watch
        --set osparc.vcsOriginUrl='"${VCS_URL}"'
        --set osparc.vcsRef='"${VCS_REF}"'
        --set osparc.vcsRefClient='"${VCS_REF_CLIENT}"'
        --set osparc.vcsStatusClient='"${VCS_STATUS_CLIENT}"'
  webserver:
    image: services_webserver:dev
    build:
      target: development
    volumes:
      - ./web/server:/devel/services/web/server
      - ./web/client/source-output:/devel/services/web/client
      - ../packages:/devel/packages
    stdin_open: true
    tty: true
    environment:
      - SC_BOOT_MODE=debug-ptvsd
    ports:
      - "3001:3000"
    depends_on:
      - webclient
