#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

before_install() {
    bash ci/travis/helpers/install_docker_compose;
    bash ci/travis/helpers/show_system_versions;
    bash ci/travis/helpers/check_changes.sh devpi/;
    env
}

install() {
    echo "nothing to install..."
}

before_script() {
    echo "nothing to do..."
}

script() {
    test="$DOCKER_PASSWORD"
    echo test
    test2="$DOCKER_USERNAME"
    echo test2
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    pushd devpi; make release; popd
}

after_success() {
    echo "Release succeeded"
    pushd devpi; make info-image; popd
}

after_failure() {
    echo "Release failed"
    env
    docker images
}


# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
