# Registries contains access credentials to repositories
# these can be used as input (source) or output (destination)
# env_user and env_password refer to environment variables containing the credentials
registries:
  dockerhub:
    # generally used only as source
    url: index.docker.io # dockerhub
    env_user: ENV_VAR_USERNAME_DOCKERHUB
    env_password: ENV_PASSWORD_DOCKERHUB
  master:
    url: master:5000
    env_user: ENV_VAR_USERNAME_MASTER
    env_password: ENV_PASSWORD_MASTER
    skip-tls-verify: true
  staging:
    url: staging:5000
    env_user: ENV_VAR_USERNAME_STAGING
    env_password: ENV_PASSWORD_STAGING
    skip-tls-verify: true
  aws:
    url: aws:5000
    env_user: ENV_VAR_USERNAME_AWS
    env_password: ENV_PASSWORD_AWS
    skip-tls-verify: true

# the scheduler will try to run all stages in parallel
# if a stage has a depends_on key it will wait for previous stages
# to complete before starting
stages:
  # generic usage
  - from:
      source: "dockerhub" # key comes from above registries definition
      repository: "itisfoundation/sleeper"
    to:
      - destination: master # key comes from above registries definition
        repository: "simcore/services/comp/sleeper"
        tags: [] # will take all available tags
      - destination: staging # key comes from registries
        repository: "simcore/services/comp/sleeper"
        tags: ["1.0.0"] # specify a tag
      - destination: aws # key comes from registries
        repository: "simcore/services/comp_v3/sleeper" # different namespace is also allowed
        tags: ["0.0.1", "1.0.0"] # specify multiple tags
    id: "i-am-not-required" # optional, not needed here

  # more advanced usage
  # pulls all sleeper tags from dockerhub and pushes to master
  # to run this stage before another one, give it an id so it can be 
  # referred by other stages
  - from:
      source: "dockerhub"
      repository: "itisfoundation/sleeper"
    to:
      - destination: master
        repository: "simcore/services/comp/sleeper"
        tags: []
    id: "i-run-before"  # needed for the stage below
  
  # because the depends_on tag was added, this stage will wait for the specified
  # sages to complete before starting
  # Please note: if an error occurs in one of the depends_on stages execution
  # still goes on. Error logs will always be displayed if something went wrong
  # for easy debugging
  - from:
      source: "master"
      repository: "simcore/services/comp/sleeper"
    to:
      - destination: staging
        repository: "simcore/services/comp_v4/sleeper"
        tags: ["1.0.0"]
    depends_on: ["i-run-before"]
