dist: bionic
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.1
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
      - expect-dev # for unbuffer: brings color back into travis logs
stages:
  - build
  - test
  - release

jobs:
  include:
    - stage: build
      name: devpi
      language: python
      sudo: required
      python:
        - "3.7"
      cache: pip
      before_install:
        - sudo bash ci/travis/build/devpi before_install || travis_terminate 0
      install:
        - unbuffer bash ci/travis/build/devpi install
      before_script:
        - unbuffer bash ci/travis/build/devpi before_script
      script:
        - unbuffer bash ci/travis/build/devpi script
      after_success:
        - unbuffer bash ci/travis/build/devpi after_success
        
    - stage: build
      # in pull request we do not have credentials to push, so this is useless
      if: NOT type = pull_request AND tag IS blank
      name: build images
      language: minimal
      sudo: required
      before_install:
        - sudo bash ci/travis/build/rabbit-mq before_install || travis_terminate 0
      install:
        - unbuffer bash ci/travis/build/rabbit-mq install
      before_script:
        - unbuffer bash ci/travis/build/rabbit-mq before_script
      script:
        - unbuffer bash ci/travis/build/rabbit-mq script
      after_success:
        - unbuffer bash ci/travis/build/rabbit-mq after_success
      after_failure:
        - unbuffer bash ci/travis/build/rabbit-mq after_failure
      deploy:
        - provider: script
          skip_cleanup: true
          script: unbuffer bash ci/travis/build/rabbit-mq deploy
          on:
            all_branches: true

    - stage: test
      name: devpi test
      language: python
      sudo: required
      python:
        - "3.7"
      cache: pip
      before_install:
        - sudo bash ci/travis/tests/devpi before_install
      install:
        - unbuffer bash ci/travis/tests/devpi install
      before_script:
        - unbuffer bash ci/travis/tests/devpi before_script
      script:
        - unbuffer bash ci/travis/tests/devpi script
      after_success:
        - unbuffer bash ci/travis/tests/devpi after_success

    - stage: release
      name: devpi release
      language: python
      sudo: required
      python:
        - "3.7"
      cache: pip
      before_install:
        - sudo bash ci/travis/release/devpi before_install
      install:
        - unbuffer bash ci/travis/release/devpi install
      before_script:
        - unbuffer bash ci/travis/release/devpi before_script
      script:
        - unbuffer bash ci/travis/release/devpi script
      after_success:
        - unbuffer bash ci/travis/release/devpi after_success