dist: bionic
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.1
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
      - expect-dev # for unbuffer: brings color back into travis logs

jobs:
  include:
    # build images ----------------------------------------------------------------------
    - stage: build
      # in pull request we do not have credentials to push, so this is useless
      if: NOT type = pull_request AND tag IS blank
      name: build images
      language: minimal
      sudo: required
      before_install:
        - sudo bash ci/travis/build/rabbit-mq before_install
      install:
        - unbuffer bash ci/travis/build/rabbit-mq install
      before_script:
        - unbuffer bash ci/travis/build/rabbit-mq before_script
      script:
        - unbuffer bash ci/travis/build/rabbit-mq script
      after_success:
        - unbuffer bash ci/travis/build/rabbit-mq after_success
      after_failure:
        - unbuffer bash ci/travis/build/rabbit-mq after_failure
      deploy:
        - provider: script
          skip_cleanup: true
          script: unbuffer bash ci/travis/build/rabbit-mq deploy
          on:
            all_branches: true
