dist: bionic
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.1
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
      - expect-dev # for unbuffer: brings color back into travis logs


stages:
  - build
  - test
  - release

jobs:
  include:
      
    - stage: build
      if: branch = master
      name: devpi
      language: python
      python:
        - "3.7"
      cache: pip
      before_install:
        - sudo bash ci/build/devpi before_install
      install:
        - unbuffer bash ci/build/devpi install
      before_script:
        - unbuffer bash ci/build/devpi before_script
      script:
        - unbuffer bash ci/build/devpi script
      after_success:
        - unbuffer bash ci/build/devpi after_success
        
    - stage: build
      # in pull request we do not have credentials to push, so this is useless
      if: NOT type = pull_request AND tag IS blank
      name: build images
      language: minimal
      sudo: required
      before_install:
        - sudo bash ci/travis/build/rabbit-mq before_install
      install:
        - unbuffer bash ci/travis/build/rabbit-mq install
      before_script:
        - unbuffer bash ci/travis/build/rabbit-mq before_script
      script:
        - unbuffer bash ci/travis/build/rabbit-mq script
      after_success:
        - unbuffer bash ci/travis/build/rabbit-mq after_success
      after_failure:
        - unbuffer bash ci/travis/build/rabbit-mq after_failure
      deploy:
        - provider: script
          skip_cleanup: true
          script: unbuffer bash ci/travis/build/rabbit-mq deploy
          on:
            all_branches: true

    - stage: test
          if: branch = master
          name: devpi test
          language: python
          python:
            - "3.7"
          cache: pip
          before_install:
            - sudo bash ci/tests/devpi before_install
          install:
            - unbuffer bash ci/tests/devpi install
          before_script:
            - unbuffer bash ci/tests/devpi before_script
          script:
            - unbuffer bash ci/tests/devpi script
          after_success:
            - unbuffer bash ci/tests/devpi after_success


    - stage: release
          if: branch = master
          name: devpi release
          language: python
          python:
            - "3.7"
          cache: pip
          before_install:
            - sudo bash ci/release/devpi before_install
          install:
            - unbuffer bash ci/release/devpi install
          before_script:
            - unbuffer bash ci/release/devpi before_script
          script:
            - unbuffer bash ci/release/devpi script
          after_success:
            - unbuffer bash ci/release/devpi after_success