version: "3.7"
services:
  auto-deployment-agent:
    build:
      target: development
    image: deployment-agent:dev
    volumes:
      - ./:/devel/services/deployment-agent
    environment:
      - SC_BOOT_MODE=debug-ptvsd
    ports:
      - "3005:3000"
    configs:
      - source: deployment_config
        target: /home/scu/host-dev.yaml
