version: '3.7'
services:
  qooxdoo-kit:
    image: ${DOCKER_REPO:-itisfoundation}/qooxdoo-kit:${VERSION:-lastbuild}
    # init: true See #11
    build:
      context: .
      cache_from:
        - itisfoundation/qooxdoo-kit:latest
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        swiss.itis.dockerfiles.swagger-cli.version  : "${APP_VERSION}"
