## Runtime configuration for the simcore_service_deployment_agent application.
##
version: '1.0'
rest:
  version: v0
  location: oas3/v0/openapi.yaml
main:
  log_level: WARNING
  host: 127.0.0.1
  port: 8888
  watched_git_repositories:
  # all git repositories that shall be controlled
    - id: git-repo-id
      url: https-style-repository-url
      branch: optional-branch-name-or-master
      pull_only_files: false # if true will only pull the files define in paths
      paths:
        # lists the files where to look for changes in the repo
        - services/docker-compose.yml
  docker_private_registries:
    # lists registries and their credentials if necessary to check for services to download from
    - url: https://index.docker.io/v1
      username: the-username
      password: the-password
  docker_stack_recipe:
    # defines the recipe to generate the docker-compose style stack file to be deployed in the swarm
    # An optional command line may be defined to that end that generate the docker-compose file.
    files:
      # lists the files that shall be copied from the git repos above
      - id: git-repo-id
        paths:
          - services/docker-compose.yml
    workdir: git-repo-id # defines where the files above shall be copied. Can be defined as temp also to copy them in a temporary directory
    command: make create-staging-stack-file output_file=stack.yml
    stack_file: stack.yml # the output file of the command above, or just the file to use
    excluded_services: []
    excluded_volumes: []
    additional_parameters: {}
  portainer:
    # lists the portainer instances to call upon
    - url: http://localhost:9000
      username: the-username
      password: the-password
      stack_name: the-stack-name
  polling_interval: 30
  notifications:
      - service: mattermost
        url: mattermost_url
        message: "[A new staging version of oSparc has been deployed !!!](the_url_to_go_for/)"
        enabled: true
        channel_id: dfsfdsfsf
        personal_token: some_token
