version: '3.7'
services:
  pip-kit:
    image: itisfoundation/pip-kit:latest
    build:
      context: .
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
    volumes:
      - .:/home/itis/work