version: '3.7'
services:
  python-with-pandas:
    image: itisfoundation/python-with-pandas:3.6-alpine
    build:
      context: ./3.6-alpine
      target: runtime-image
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
