name: Deployment-agent

on:
  push:
  pull_request:

jobs:
  unit-test-deployment-agent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7]
        os: [ubuntu-18.04]
      fail-fast: false
    name: Unit-testing deployment-agent
    steps:
      - name: Exit with success
        run: exit 0

  system-test-deployment-agent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7]
        os: [ubuntu-18.04]
      fail-fast: false
    name: System-testing deployment-agent
    steps:
      - name: Exit with success
        run: exit 0
