name: Docker octave

on: [push, pull_request]

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          cd octave
          make build-nc

      - name: Run tests
        run: |
          cd octave
          make test
