name: rabbitmq CI

on:
  pull_request:
    branches:
      - "*"
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'rabbitmq/**'
  push:
    branches:
      - master
    paths:
      - 'rabbitmq/**'

jobs:
  build-docker-registry-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          pushd rabbitmq
          make build

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          pushd rabbitmq
          make push

